version: '3'
services:
   ruby:
     build:
        context: ./cucumber
        dockerfile: Dockerfile
 #    restart: always
     image: alyssontkd/cucumber
     container_name: 'cucumber'
     privileged: true
#     command: Xvfb :20 -screen 0 1366x768x16
     command: tail -f /dev/null
     shm_size: 512M
     environment:
        - DISPLAY=:99
        - APPLICATION_ENV=development
     volumes:
        - /var/www/docker/cucumber-docker/cucumber/projeto-qa:/usr/src/app/cucumber-estrutura
     tty: true
