# frozen_string_literal: true

 source "http://rubygems.org"

 gem 'capybara'
 gem 'cucumber'
 gem 'faker'
 gem 'rspec'
 gem 'selenium-webdriver'
 gem 'site_prism'
 #gem 'database_cleaner'

 # gem "rails"
